CREATE TABLE users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  username VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE lists (
  list_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  created_by INTEGER NOT NULL,
  title TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE permissions (
  permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  from_user INTEGER NOT NULL,
  to_user INTEGER NOT NULL,
  list_id INTEGER NOT NULL,
  perm_type INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE list_points (
  point_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  list_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  position INTEGER NOT NULL,
  checked BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  added_by INTEGER NOT NULL
);

CREATE TABLE permission_type (
  type_id INTEGER PRIMARY KEY NOT NULL,
  description TEXT NOT NULL
);

-- Foreign Key Constraints
ALTER TABLE permissions
  ADD FOREIGN KEY (perm_type) REFERENCES permission_type (type_id);

ALTER TABLE list_points
  ADD FOREIGN KEY (list_id) REFERENCES lists (list_id);

ALTER TABLE permissions
  ADD FOREIGN KEY (from_user) REFERENCES users (user_id);

ALTER TABLE permissions
  ADD FOREIGN KEY (to_user) REFERENCES users (user_id);

ALTER TABLE permissions
  ADD FOREIGN KEY (list_id) REFERENCES lists (list_id);

ALTER TABLE lists
  ADD FOREIGN KEY (created_by) REFERENCES users (user_id);

ALTER TABLE list_points
  ADD FOREIGN KEY (added_by) REFERENCES users (user_id);

INSERT INTO permission_type VALUES (0, 'owner');
INSERT INTO permission_type VALUES (1, 'edit');
INSERT INTO permission_type VALUES (2, 'read-only');
INSERT INTO permission_type VALUES (3, 'no-permission');
