// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type List struct {
	ListID    int32     `json:"list_id"`
	CreatedBy int32     `json:"created_by"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
}

type ListPoint struct {
	PointID   int32     `json:"point_id"`
	ListID    int32     `json:"list_id"`
	Content   string    `json:"content"`
	Position  int32     `json:"position"`
	Checked   bool      `json:"checked"`
	CreatedAt time.Time `json:"created_at"`
	AddedBy   int32     `json:"added_by"`
}

type Permission struct {
	PermissionID int32     `json:"permission_id"`
	FromUser     int32     `json:"from_user"`
	ToUser       int32     `json:"to_user"`
	ListID       int32     `json:"list_id"`
	PermType     int32     `json:"perm_type"`
	CreatedAt    time.Time `json:"created_at"`
}

type PermissionType struct {
	TypeID      int32  `json:"type_id"`
	Description string `json:"description"`
}

type User struct {
	UserID    int32     `json:"user_id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
