// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type List struct {
	ListID    int32     `json:"list_id"`
	CreatedBy int32     `json:"created_by"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
}

type ListPoint struct {
	PointID   int32     `json:"point_id"`
	ListID    int32     `json:"list_id"`
	Point     []string  `json:"point"`
	Checked   bool      `json:"checked"`
	CreatedAt time.Time `json:"created_at"`
}

type Permission struct {
	PermissionID int32     `json:"permission_id"`
	ListID       int32     `json:"list_id"`
	UserID       int32     `json:"user_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	UserID    int32     `json:"user_id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
