// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddPermission(ctx context.Context, arg AddPermissionParams) (Permission, error)
	CheckPoint(ctx context.Context, pointID int32) error
	CountUsers(ctx context.Context) (int64, error)
	CreateList(ctx context.Context, arg CreateListParams) (List, error)
	CreatePoint(ctx context.Context, arg CreatePointParams) (ListPoint, error)
	CreateUser(ctx context.Context, username string) (User, error)
	DeletePermission(ctx context.Context, arg DeletePermissionParams) error
	DeleteUser(ctx context.Context, userID int32) error
	EditTile(ctx context.Context, arg EditTileParams) error
	GetUser(ctx context.Context, userID int32) (User, error)
	UncheckPoint(ctx context.Context, pointID int32) error
	UserPoints(ctx context.Context, userID int32) ([]UserPointsRow, error)
}

var _ Querier = (*Queries)(nil)
